apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "hollowtrees.fullname" . }}"
  labels:
    app.kubernetes.io/name: {{ template "hollowtrees.name" . }}
    helm.sh/chart: {{ template "hollowtrees.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
data:
  config.yaml: |-
    global:
        bindAddr: ":{{ .Values.port }}"
        buffersize: {{ .Values.buffersize }}

    # logger settings
    log:
        format: "{{ .Values.logFormat }}"
        level: "{{ .Values.logLevel }}"

    # action plugin settings
    action_plugins:
      {{if .Values.k8splugin.enabled}}
        - name: "ht-k8s-action-plugin"
          address: "{{ .Release.Name }}-k8splugin:{{ .Values.k8splugin.port }}"
      {{end}}

      {{if .Values.asgplugin.enabled}}
        - name: "ht-aws-asg-action-plugin"
          address: "{{ .Release.Name }}-asgplugin:{{ .Values.asgplugin.port }}"
      {{end}}

    # action plugin rules
    rules:
{{ toYaml .Values.rules | indent 8 }}
