apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "hollowtrees.fullname" . }}"
  labels:
    app.kubernetes.io/name: {{ include "hollowtrees.name" $ }}
    helm.sh/chart: {{ include "hollowtrees.chart" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hollowtrees.name" $ }}
        helm.sh/chart: {{ include "hollowtrees.chart" $ }}
        app.kubernetes.io/managed-by: {{ $.Release.Service }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/version: {{ $.Chart.AppVersion | replace "+" "_" }}
        app.kubernetes.io/part-of: {{ $.Chart.Name }}
    spec:
      containers:
      - name: hollowtrees
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy | quote }}
        ports:
        - name: http
          containerPort: {{ .Values.port }}
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /health
            port: http
            httpHeaders:
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: config
          mountPath: /root/conf/
      volumes:
      - name: config
        configMap:
          name: {{ template "hollowtrees.fullname" . }}
