dependencies:
- name: traefik
  version: 1.12.1
  repository: https://kubernetes-charts.storage.googleapis.com/

- name: prometheus
  version: 4.6.9
  repository: https://kubernetes-charts.storage.googleapis.com/



