apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: {{ .Release.Namespace }}
  labels:
    spark-version: {{ .Values.spark.version }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: spark-edit
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Chart.Name }}-{{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
