apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "name" . }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/proxy-body-size: 8m
spec:
  rules:
  - http:
      paths:
        - path: /spark-rss
          backend:
            serviceName: "{{ .Values.app.service.name }}"
            servicePort: {{ .Values.app.service.externalPort }}