apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-tomcat
  namespace: default
  labels:
    release: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: traefik

spec:
  rules:
    - http:
        paths:
          - path: /hello
            backend:
              serviceName: {{ template "fullname" . }}
              servicePort: 8080