apiVersion: v1
appVersion: 0.0.1
description: echo server chart
name: echo-server
version: 0.0.1

home: https://banzaicloud.com

maintainers:
  - name: Banzai Cloud
    email: info@banzaicloud.com

icon: https://banzaicloud.com/img/banzai-cloud-logo.png
