replicas: 2

image:
  repository: waynz0r/echo-server
  tag: "master"
  pullPolicy: Always

resources:
  limits:
   cpu: 1500m
   memory: 256Mi
  requests:
   cpu: 250m
   memory: 64Mi

serviceType: LoadBalancer

identifier: "central"
