image:
  repository: "openjdk"
  tag: "8-jdk-alpine"
  pullPolicy: "IfNotPresent"

artifactName: "gs-spring-boot-docker-0.1.0.jar"
artifactUrl: "https://s3-eu-west-1.amazonaws.com/laszlo-p"

replicas: 1

resources:
  requests:
    memory: 32Mi
    cpu: 40m
  limits:
    memory: 2Gi
    cpu: 1