apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: {{ .Release.Namespace }}
  labels:
    app: echo
    version: v1
    {{ include "echo-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: echo
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: echo
        version: v1
    spec:
      containers:
      - name: echo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: IDENTIFIER
          value: "{{ .Values.identifier }}"
        {{- with .Values.resources }}
        resources:
          {{ toYaml . | nindent 12 }}
        {{- end }}
